services:
  ms-auth:
    build: .
    container_name: fs3-ms-sync
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always