spring.application.name=ms_sync

# Puerto del servidor (usamos 8083 para no chocar con Auth (8080) ni Weather (8082))
server.port=8083

# Configuración de MongoDB Local (por defecto puerto 27017)
spring.data.mongodb.uri=mongodb://localhost:27017/wardrobe_sync_db
spring.data.mongodb.database=wardrobe_sync_db

# Clave secreta JWT (DEBE ser exactamente la misma que tienes configurada en tu MS de Auth)
jwt.secret=EstaEsUnaClaveSecretaSuperSeguraDeAlMenos256BitsParaProtegerElJWT
