spring.application.name=ms_sync

# Puerto del servidor (usamos 8083 para no chocar con Auth (8080) ni Weather (8082))
server.port=8083

# Configuración de MySQL para AWS RDS
spring.datasource.url=jdbc:mysql://localhost:3306/sync_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Clave secreta JWT (DEBE ser exactamente la misma que tienes configurada en tu MS de Auth)
jwt.secret=bXlTZWNyZXRLZXlGb3JKV1RUaGF0SXNBdExlYXN0MjU2Qml0c0xvbmdGb3JIUzI1NkFsZ29yaXRobUFuZFNob3VsZEJlQmFzZTY0RW5jb2RlZA==

# Configuración de AWS S3
aws.accessKeyId=YOUR_AWS_ACCESS_KEY
aws.secretKey=YOUR_AWS_SECRET_KEY
aws.region=YOUR_AWS_REGION
aws.s3.bucketName=YOUR_S3_BUCKET_NAME
aws.s3.presignedUrlExpirationMinutes=60

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CONFIGURACIÓN CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=false



aws.s3.enabled=false
aws.s3.bucketName=tu-bucket
aws.s3.presignedUrlExpirationMinutes=60